# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ALL_PROJECTS/motor_control/motor_control.srcs/sources_1/bd/design_motor_control/ip/design_motor_control_axi_gpio_1_0/design_motor_control_axi_gpio_1_0.xci
# IP: The module: 'design_motor_control_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ALL_PROJECTS/motor_control/motor_control.srcs/sources_1/bd/design_motor_control/ip/design_motor_control_axi_gpio_1_0/design_motor_control_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_motor_control_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ALL_PROJECTS/motor_control/motor_control.srcs/sources_1/bd/design_motor_control/ip/design_motor_control_axi_gpio_1_0/design_motor_control_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_motor_control_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ALL_PROJECTS/motor_control/motor_control.srcs/sources_1/bd/design_motor_control/ip/design_motor_control_axi_gpio_1_0/design_motor_control_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_motor_control_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/ALL_PROJECTS/motor_control/motor_control.srcs/sources_1/bd/design_motor_control/ip/design_motor_control_axi_gpio_1_0/design_motor_control_axi_gpio_1_0.xci
# IP: The module: 'design_motor_control_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ALL_PROJECTS/motor_control/motor_control.srcs/sources_1/bd/design_motor_control/ip/design_motor_control_axi_gpio_1_0/design_motor_control_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_motor_control_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ALL_PROJECTS/motor_control/motor_control.srcs/sources_1/bd/design_motor_control/ip/design_motor_control_axi_gpio_1_0/design_motor_control_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_motor_control_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ALL_PROJECTS/motor_control/motor_control.srcs/sources_1/bd/design_motor_control/ip/design_motor_control_axi_gpio_1_0/design_motor_control_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_motor_control_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
