set_property SRC_FILE_INFO {cfile:D:/ALL_PROJECTS/motor_control/motor_control.srcs/constrs_1/new/motor_control.xdc rfile:../../../motor_control.srcs/constrs_1/new/motor_control.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {GPIO_0_tri_o[3]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports {GPIO_0_tri_o[2]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11 [get_ports {GPIO_0_tri_o[0]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports {GPIO_0_tri_o[1]}]
