# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/motor_control.xdc

# Block Designs: bd/design_motor_control/design_motor_control.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_motor_control || ORIG_REF_NAME==design_motor_control} -quiet] -quiet

# IP: bd/design_motor_control/ip/design_motor_control_processing_system7_0_0/design_motor_control_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_motor_control_processing_system7_0_0 || ORIG_REF_NAME==design_motor_control_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_motor_control/ip/design_motor_control_axi_gpio_0_0/design_motor_control_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_motor_control_axi_gpio_0_0 || ORIG_REF_NAME==design_motor_control_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_motor_control/ip/design_motor_control_axi_gpio_1_0/design_motor_control_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_motor_control_axi_gpio_1_0 || ORIG_REF_NAME==design_motor_control_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_motor_control/ip/design_motor_control_ps7_0_axi_periph_0/design_motor_control_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_motor_control_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_motor_control_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_motor_control/ip/design_motor_control_rst_ps7_0_100M_0/design_motor_control_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_motor_control_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_motor_control_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_motor_control/ip/design_motor_control_xbar_0/design_motor_control_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_motor_control_xbar_0 || ORIG_REF_NAME==design_motor_control_xbar_0} -quiet] -quiet

# IP: bd/design_motor_control/ip/design_motor_control_auto_pc_0/design_motor_control_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_motor_control_auto_pc_0 || ORIG_REF_NAME==design_motor_control_auto_pc_0} -quiet] -quiet

# XDC: bd/design_motor_control/design_motor_control_ooc.xdc
